# Generated by Django 4.0.5 on 2022-06-20 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='neighborhood.profile'),
        ),
    ]
